### ISSUE TITLE
Unable to verify contract on Etherscan (Ropsten)

### ISSUE THREAD

**Issue by gokselp** [ZentaChain/CHAIN#1]
I think this has something to do with Etherscan or try it with the solidity version 0.8.1

**Comment by ZentaChainAdmin** [comment]
@gokselp Yes I try it also 2 times we should change to hardhat and dump the version of solidity ^0.6

**Comment by ZentaChainAdmin** [comment]
@gokselp [OpenZeppelin/openzeppelin-contracts/issues/2570] still in beta we should dump the version.

**Comment by gokselp** [comment]
Openzeppelin support for Solidity 0.8 has not been officially released.

**Comment by ZentaChainAdmin** [comment]
This is not issue of Etherscan, Solidity or Openzeppelin but the truffle compiler in unable to find the contract on Etherscan. We have used [hardhat](https://hardhat.org/) and bump the version of the compiler to `0.9.0.` I am closing the issue.
```
Compiling 1 file with 0.8.0
Successfully submitted source code for contract
contracts/Zentachain.sol:Zentachain at 0x07629C41c0416500BFF1fA6F855b73fB2e552C87

Successfully verified contract Zentachain on Etherscan.
https://ropsten.etherscan.io/address/0x07629C41c0416500BFF1fA6F855b73fB2e552C87#code
```
